# Generated by Django 4.2.1 on 2023-05-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_carplate_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tel", models.CharField(blank=True, max_length=255, null=True)),
                ("invoice_no", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.CharField(blank=True, max_length=255, null=True)),
                ("bill_to", models.CharField(blank=True, max_length=255, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank_account",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "total_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("image", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
